"""Msg tabl

Revision ID: 1b6c927a4241
Revises: 80b656ddcb4b
Create Date: 2023-06-27 13:09:39.278277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6c927a4241'
down_revision = '80b656ddcb4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('msg', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_msg_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('msg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_msg_timestamp'))

    op.drop_table('msg')
    # ### end Alembic commands ###
